name: Build
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        compiler: [msvc, clang-cl]
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
 
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
 
      - name: Setup MSVC dev environment
        uses: ilammy/msvc-dev-cmd@v1
 
      - name: Configure CMake (msvc)
        if: matrix.compiler == 'msvc'
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl
 
      - name: Configure CMake (clang-cl)
        if: matrix.compiler == 'clang-cl'
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl
 
      - name: Build
        run: cmake --build build
 
 